export const projects = [
  {
    title: 'Weather App',
    description: "A simple weather application created using a free weather API, AccuWeather. Enter any location to get the weather along with a graphic! Demonstrates JavaScript experience with async, fetch, promises, and await.",
      image: '/images/1.png',
      tags: ['JavaScript', 'API'],
    source: 'https://google.com',
    visit: 'https://github.com/rjrillon/weather-app',
    id: 0,
  },
  {
    title: 'My Portfolio',
    description:"The website you are currently viewing right now! Created using React and Next.",
    image: '/images/2.png',
    tags: ['JavaScript','React', 'Next'],
    source: 'https://github.com',
    visit: 'https://github.com',
    id: 1,
  },
  {
    title: 'Real-Time Chatroom',
    description: "A live chatroom with different discussion rooms to talk with others that share your interests. Uses Firestore database and demonstrates JavaScript experience using OOP and other common techniques.",
      image: '/images/3.png',
      tags: ['JavaScript', 'Firebase'],
    source: 'https://github.com/rjrillon/chatroom',
    visit: 'https://github.com/rjrillon/chatroom',
    id: 2,
  },
  {
    title: 'Magic Match',
    description: "A dynamic image-matching memory game to demonstrate experience with React hooks.",
    image: '/images/4.png',
    tags: ['JavaScript', 'React'],
    source: 'https://github.com/rjrillon/magic_match',
    visit: 'https://github.com/rjrillon/magic_match',
    id: 3,
  },
  {
    title: 'Rainbow Reef',
    description: "A 2D brick-breaker game I made for one of my course projects. Has ricochet physics and a scoring system. Created using Java Swing, Maven, and Node.",
    image: '/images/5.png',
    tags: ['Java', 'Node', 'Maven', 'Swing'],
    source: 'https://github.com/rjrillon/rainbowreef',
    visit: 'https://github.com/rjrillon/rainbowreef',
    id: 4,
  },
  {
    title: 'Text File Word-Reader',
    description: "A C program to read a large text file to find the top 10 most occurring words at least 6 characters long. A student assignment that demonstrates experience with C programming, using the command line, a bubble sorting algorithm, and use of threads and thread-safe functions with buffers.",
    image: '/images/6.png',
    tags: ['C', 'Linux','Bubble Sort','Threads','Buffers'],
    source: 'https://github.com/rjrillon/textfile_wordreader',
    visit: 'https://github.com/rjrillon/textfile_wordreader',
    id: 5,
  },
  {
    title: 'Todo List',
    description: "An interactive application in which you can search, delete, and add to a locally stored to-do list.",
    image: '/images/7.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/rjrillon/todo-list',
    visit: 'https://github.com/rjrillon/todo-list',
    id: 6,
  },
  {
    title: 'Ninja Quiz',
    description: "A simple and interactive quiz to determine if you are a ninja!",
    image: '/images/8.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: 'https://github.com/rjrillon/ninja-quiz',
    visit: 'https://github.com/rjrillon/ninja-quiz',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'The start of my CS journey', },
  { year: 2020, text: 'This is a timeline carousel', },
  { year: 2021, text: 'Use mobile view to see how it works!', },
  { year: 2022, text: 'Swipe from left to right', },
  { year: 2023, text: 'And be slightly amazed!', },
];